name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3
      
      # Step 2: Install backend dependencies
      - name: Install backend deps
        run: |
          cd backend
          npm install

      # Step 3: Run npm audit for dependency vulnerabilities
      - name: Dependency vulnerability check (npm audit)
        run: |
          cd backend
          npm audit --audit-level=high

      # Step 4: Install frontend dependencies
      - name: Install frontend deps
        run: |
          cd frontend
          npm install
      
      # Step 5: Run frontend build
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Step 6: Run tests
      - name: Run tests
        run: |
          cd backend
          npm test     

      # Step 7: SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=schinojr-org
            -Dsonar.projectKey=Oluwakomiyo_NYCAD-sndx
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    

      # Step 8: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} ./backend

      # Step 9: Run Trivy vulnerability scan
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ./backend
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'