name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v3
      
      # Step 2: Install backend dependencies
      - name: Install backend deps
        run: |
          cd backend
          npm install

      # Step 3: Install frontend dependencies
      - name: Install frontend deps
        run: |
          cd frontend
          npm install
      
      # Step 4: Run frontend build
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Step 5: Run tests
      - name: Run tests
        run: |
          cd backend
          npm test     